<?php
session_start();
header('Content-Type: application/json; charset=UTF-8');

if ($_SERVER['REQUEST_METHOD'] !== 'POST') {
    http_response_code(405);
    echo json_encode(['error' => 'Method not allowed']);
    exit();
}

if (!isset($_SESSION['logged_in']) || $_SESSION['logged_in'] !== true) {
    http_response_code(401);
    echo json_encode(['error' => 'Unauthorized']);
    exit();
}

$input = json_decode(file_get_contents('php://input'), true);
if (!is_array($input)) {
    http_response_code(400);
    echo json_encode(['error' => 'Invalid JSON payload']);
    exit();
}

$email = isset($input['email']) ? trim($input['email']) : '';
$reportId = isset($input['report_id']) ? intval($input['report_id']) : 0;
$pdfBase64Uri = isset($input['pdf_base64']) ? trim($input['pdf_base64']) : '';

if ($email === '' || $reportId <= 0 || $pdfBase64Uri === '') {
    http_response_code(400);
    echo json_encode(['error' => 'Missing required fields: email, report_id, pdf_base64']);
    exit();
}

if (!filter_var($email, FILTER_VALIDATE_EMAIL)) {
    http_response_code(400);
    echo json_encode(['error' => 'Invalid email address']);
    exit();
}

$pdfBase64 = $pdfBase64Uri;

if (stripos($pdfBase64Uri, 'data:') === 0) {
    $commaPos = strpos($pdfBase64Uri, ',');
    if ($commaPos === false) {
        http_response_code(400);
        echo json_encode(['error' => 'Invalid PDF data URI format']);
        exit();
    }
    $pdfBase64 = substr($pdfBase64Uri, $commaPos + 1);
}

$pdfBase64 = rawurldecode($pdfBase64);
$pdfBase64 = str_replace(['-', '_'], ['+', '/'], $pdfBase64);
$pdfBase64 = preg_replace('/\s+/', '', $pdfBase64);

if ($pdfBase64 === null || $pdfBase64 === '') {
    http_response_code(400);
    echo json_encode(['error' => 'Invalid PDF base64 data']);
    exit();
}

$pdfBinary = base64_decode($pdfBase64, true);
if ($pdfBinary === false) {
    $padding = strlen($pdfBase64) % 4;
    if ($padding > 0) {
        $pdfBase64 .= str_repeat('=', 4 - $padding);
        $pdfBinary = base64_decode($pdfBase64, true);
    }
}

if ($pdfBinary === false) {
    http_response_code(400);
    echo json_encode(['error' => 'Failed to decode PDF data (invalid base64 payload)']);
    exit();
}

$boundary = '==Multipart_Boundary_x' . md5((string)microtime(true)) . 'x';
$subject = 'Analytics Report #' . $reportId;

$fromDomain = isset($_SERVER['HTTP_HOST']) ? preg_replace('/:\\d+$/', '', $_SERVER['HTTP_HOST']) : 'localhost';
$fromHeader = 'no-reply@' . $fromDomain;

$headers = "From: {$fromHeader}\r\n";
$headers .= "Reply-To: {$fromHeader}\r\n";
$headers .= "MIME-Version: 1.0\r\n";
$headers .= "Content-Type: multipart/mixed; boundary=\"{$boundary}\"\r\n";

$bodyText = "Analytics report #{$reportId} is attached as a PDF.\r\nGenerated by Reporting Dashboard.";
$attachment = chunk_split(base64_encode($pdfBinary));

$message = '';
$message .= "--{$boundary}\r\n";
$message .= "Content-Type: text/plain; charset=\"UTF-8\"\r\n";
$message .= "Content-Transfer-Encoding: 7bit\r\n\r\n";
$message .= $bodyText . "\r\n\r\n";
$message .= "--{$boundary}\r\n";
$message .= "Content-Type: application/pdf; name=\"analytics-report-{$reportId}.pdf\"\r\n";
$message .= "Content-Transfer-Encoding: base64\r\n";
$message .= "Content-Disposition: attachment; filename=\"analytics-report-{$reportId}.pdf\"\r\n\r\n";
$message .= $attachment . "\r\n";
$message .= "--{$boundary}--\r\n";

$sent = mail($email, $subject, $message, $headers);

if (!$sent) {
    http_response_code(500);
    echo json_encode(['error' => 'Failed to send email']);
    exit();
}

echo json_encode(['message' => 'Report emailed successfully']);
